. ${_lib_root}/coriolis/update/cache.f

. ${_lib_root}/coriolis/get/deployments.f

. ${_lib_root}/coriolis/get/endpoints.f
. ${_lib_root}/coriolis/get/endpoints/destination/options.f
. ${_lib_root}/coriolis/get/endpoints/source/options.f
. ${_lib_root}/coriolis/get/endpoints/networks.f
# . ${_lib_root}/coriolis/get/endpoints/options.f
. ${_lib_root}/coriolis/get/endpoints/storage.f

. ${_lib_root}/coriolis/get/transfers.f
. ${_lib_root}/coriolis/get/transfers/schedules.f

# . ${_lib_root}/coriolis/list/transfers.f
# . ${_lib_root}/coriolis/list/transfers/schedules.f

