# . ${_lib_root}/927/secretservice/get/cicd.f
# . ${_lib_root}/927/secretservice/get/jobserver.f
# . ${_lib_root}/927/secretservice/get/ociconfig.f
# . ${_lib_root}/927/secretservice/get/ocikeyfile.f
# . ${_lib_root}/927/secretservice/get/role.f
# . ${_lib_root}/927/secretservice/get/secrets.f
# . ${_lib_root}/927/secretservice/get/workerserver.f

. ${_lib_root}/secretservice/create/secret.f
. ${_lib_root}/secretservice_bitwarden.l