import org.apache.commons.logging.Log
import org.apache.commons.logging.LogFactory
import org.apache.hadoop.conf.Configuration
import org.apache.hadoop.hbase.ClusterStatus
import org.apache.hadoop.hbase.HConstants
import org.apache.hadoop.hbase.HBaseConfiguration
import org.apache.hadoop.hbase.client.HBaseAdmin
import org.apache.hadoop.hbase.client.Get
import org.apache.hadoop.hbase.client.Scan
import org.apache.hadoop.hbase.client.HTable
import org.apache.hadoop.hbase.client.ConnectionFactory
import org.apache.hadoop.hbase.filter.FirstKeyOnlyFilter
import org.apache.hadoop.hbase.HRegionInfo
import org.apache.hadoop.hbase.master.RegionState
import org.apache.hadoop.hbase.ServerName
import org.apache.hadoop.hbase.TableName
import org.apache.hadoop.hbase.util.Bytes
import org.apache.hadoop.hbase.util.Pair
import org.apache.hadoop.hbase.util.Writables
import org.apache.hadoop.hbase.UnknownRegionException
import org.apache.hadoop.hbase.zookeeper.MetaTableLocator
import org.apache.hadoop.hbase.zookeeper.ZooKeeperWatcher
include Java
require 'set'
